# Book settings
title: Bioinformatique médicale
author: BioinfoDiag
logo: logo.png
copyright: "GNU GENERAL DOCUMENTATION - 2020"


repository:
  url: https://github.com/BioInfoDiag/bioinformatique_medicale


latex:
  latex_documents:
    targetname: book.tex
